### ISSUE TITLE
TopoJSON/GeoJSON/MVT parsing results in different filter behavior and geometries

### ISSUE THREAD

**Issue by tallytalwar** [tangrams/tangram-es#1016]
Example Scene File:

```
cameras:
    perspective-camera:
        # Manhattan
        position: [-74.00976419448854, 40.70532700869127, 16]
        type: perspective
        fov: 45
        max_tilt: [[2, 0], [16, 90]]
        active: true

sources:
    osm:
        type: MVT
        url:  https://tile.mapzen.com/mapzen/vector/v1/all/{z}/{x}/{y}.mvt
        #type: TopoJSON
        #url:  https://tile.mapzen.com/mapzen/vector/v1/all/{z}/{x}/{y}.topojson
        #type: GeoJSON
        #url:  https://tile.mapzen.com/mapzen/vector/v1/all/{z}/{x}/{y}.json
        max_zoom: 16
        url_params:
            api_key: vector-tiles-HqUVidw

layers:
    roads:
        data: { source: osm }
        filter:
            not: { kind: [rail] }
        draw:
            lines:
                width: 1px
                order: function() { return feature.sort_rank; }
                outline:
                    order: 352

        highway:
            filter: { kind: highway, $zoom: { min: 8 } }
            draw:
                lines:
                    color: red
                    width: [[8, 2px], [9, 2.5px], [14, 4.0px], [15, 6.0px], [16, 6.5px], [17, 20m]]
                    outline:
                        color: white
                        width: [[9, 0.5px], [12, 1px], [16, 2px], [18, 6px]]
            tunnel:
                filter: {is_tunnel: true, $zoom: {min: 13} }
                draw:
                    lines:
                        color: green
                        outline:
                            color: black
```
- With MVT datasource:
  ![mvt](https://cloud.githubusercontent.com/assets/360641/19398341/3216ecea-921a-11e6-844c-6e9c29c5dc93.png)
- With TopoJSON datasource:
  ![topo](https://cloud.githubusercontent.com/assets/360641/19398357/3faed53e-921a-11e6-94ae-949864d0668e.png)
- With GeoJSON datasource:
  ![geo](https://cloud.githubusercontent.com/assets/360641/19398371/4e082be4-921a-11e6-9d08-a9cbc49e8309.png)

JS gives same results with all 3 datasources, and it matches what we get from MVT from ES.
