### ISSUE TITLE
Feature Request: Support meters as size unit for points

### ISSUE THREAD

**Issue by westnordost** [tangrams/tangram-es#1121]
I am trying to show the accuracy radius of a location around the user. Here, I ran into some problems. I think part of it is a bug, part of it is a missing feature probably.

The relevant portion of the style file:
```
styles:
    location-radius:
        base: points
        blend: overlay
        blend_order: 2
layers:
    streetcomplete_location:
        data: { source: streetcomplete_location }
        draw:
            location-radius:
                collide: false
                color: '#44fd6c3e'
                size: function() { return feature.radius }
```
and the code
```
locationLayer.clear();
LngLat pos = new LngLat(location.getLongitude(), location.getLatitude());
int accuracy = (int)(Math.ceil(location.getAccuracy()));

Map<String, String> props = new HashMap<>();
props.put("type", "point");
props.put("radius", ""+accuracy+"m");
locationLayer.addPoint(pos, props);
```

However, this gives i.e. the error:
`styleParam.cpp:184: Invalid size parameter '22m'`

If I set a static size in the style definition, I get no error, but it doesn't seem to show at all.

So my guess is that meters as a size unit for points is simply not implemented as there hasn't been a use case for this (until now :-P). At least it is not documented. That Tangram-ES does not report an error if you write `size: 50m` seems to be a bug then.
In any case, this ticket shall be a feature request to support meters as a unit for points.

Plan B for the use case I have in mind would be to use a circle-polygon for the radius, but I find that rather ugly.
