### ISSUE TITLE
Texture with no sprites displayed upside-down

### ISSUE THREAD

**Issue by westnordost** [tangrams/tangram-es#1122]
If I have just this in the style definition:
```
textures:
    location:
        url: images/position.png
        filtering: mipmap
styles:
    location-icon:
        base: points
        texture: location
        blend: overlay
        blend_order: 1
layers:
    streetcomplete_location:
        data: { source: streetcomplete_location }
        draw:
            location-icon:
                collide: false
                size: 27px
```
The position.png image is displayed upside-down. (My position image is a smiley, that's why I noticed in the first place)
(-:
