### ISSUE TITLE
Polygons deform on zoom (android)

### ISSUE THREAD

**Issue by lunarflint** [tangrams/tangram-es#1133]
I encounter an issue on displaying some squares on map. (using 'com.mapzen.tangram:tangram:0.4.5')
In total there are 12 x 12 squares around the globe.

Everything looks ok upon a certain zoom level:
![1](https://cloud.githubusercontent.com/assets/23458336/20844226/d3d01e3e-b8f9-11e6-969c-767ded4f1cbc.png)

When zoomed in a little bit more:
![2](https://cloud.githubusercontent.com/assets/23458336/20844237/dee9e516-b8f9-11e6-922c-82c9ca51f090.png)

I have tried changing the style to "lines" / "points" and the polygon outlines also deform like what you see above. I also note that more squares deform if I remove the gap between each square, don't know if this is related.

Here is the code:
```
        for(int j = 0; j < 12; ++j) {
            for(int i = 0; i < 12; ++i) {
                List<List<LngLat>> xss = new ArrayList<>(1);
                List<LngLat> xs = new ArrayList<>(4);
                xss.add(xs);
                xs.add(new LngLat(lng[i + 0], lat[j + 0]));
                xs.add(new LngLat(lng2[i + 1], lat[j + 0]));
                xs.add(new LngLat(lng2[i + 1], lat2[j + 1]));
                xs.add(new LngLat(lng[i + 0], lat2[j + 1]));
                data.addPolygon(xss, null);
            }
        }
```
and here is the style
```
layers:
    mylayer:
        data: { source: mysource }
        draw:
          mydraw:
            style: polygons
            color: [1.0, .5, .5, .5]
            order: 553     <--lowering this number won't help.
```

Is it a bug or am I doing something wrong?
Please help. Thanks.
