### ISSUE TITLE
Drawing poitns/lines using Lat Long

### ISSUE THREAD

**Issue by Nischhal** [tangrams/tangram-es#1186]
Hi
I have been trying to do some additions on the map. I tried adding a straight line on the map
 by adding some code in main.cpp. The map is displayed but the line is not. Is it possible to add a line on map by giving lat long of two points on the map? 

will glVertex3f(-0.6f, -0.4f, 0.f); be of any help here?

**Comment by karimnaaji** [comment]
Hi @Nischhal , to draw points and lines you need to refer to the [marker interface](https://github.com/tangrams/tangram-es/blob/master/core/src/tangram.h#L183_L236)/[client data sources](https://github.com/tangrams/tangram-es/blob/master/core/src/tangram.h#L173_L181).

With client data sources:

- Create a layer for it in your stylesheet:
```yaml
layers:
    line_layer:
        data: { source: my_custom_source }
        draw:
            lines:
                color: red
                order: 500
                width: 5px
```
- Create the source from the code
```cpp
Tangram::Properties properties;
auto source = std::make_shared<Tangram::ClientGeoJsonSource>("my_custom_source", "");
properties.set("line_prop", "line properties");
source->addLine(properties, {coord0, coord1, coord2});
map->addDataSource(source);
```

With markers:
```cpp
Tangram::MarkerID polyline = map->markerAdd();
map->markerSetStyling(polyline, "{ style: lines, color: red, width: 5px, order: 5000 }");
LngLat coords[3] { coord0, coord1, coord2 } ;
map->markerSetPolyline(polyline, coords, 3);
```
