### ISSUE TITLE
Adding text to a marker icon

### ISSUE THREAD

**Issue by Guillaume227** [tangrams/tangram-es#1273]
I have a marker displaying an icon:
in code I set styling to : (my scene.yaml defines 'my_icons' style)
`"{ style: 'my_icons', sprite: 'booth',  color: '#ff48ed73', collide: false, interactive: true}"`

That's working nicely.
Now I would like to add a text label to that same marker. Is that possible, or do I have to add another marker with style 'text' (as mentioned in #1094 for example)? 
I have tried several approaches without luck:
1) I tried changing styling to:
`"{ style: 'my_icons', sprite: 'booth', color: '#ff48ed73', collide: false, interactive: true, text_source: 'foo', text: {text_source: 'bar', visible: true, font: { size: 64px, fill: 'black' }}}"`
(note that I tried setting text_source in two places, inspired by what I saw in s_StyleParamMap in styleParam.cpp - I gather that not all items from that style map apply simultaneously? is there a reference anywhere of which ones can be used in combination?)

2) I tried updating style definition in scene.yaml to 
```
styles:
    my_icons:
        base: points
        texture: my_pois
        interactive: true
        text_source: 'foo'
        text:
            family: sans-serif
            weight: 400
            style: normal
            size: 64px
            fill: black
```

As a side question, can polygon features take a text label as well? 
Is there somewhere a list of properties supported by tangram-es, as opposed to general tangram?

I.e. I have tried using blend: inlay in the property map passed to addFeature but I get a StyleParam not found in the logcat. I see blend as a style parameters in the tangram doc (https://mapzen.com/documentation/tangram/styles/) but I understand trangram-es is a subset of tangram.
