### ISSUE TITLE
Android cache

### ISSUE THREAD

**Issue by ivangorelow** [tangrams/tangram-es#1309]
How can I use cache on android?

**Comment by matteblair** [comment]
@ivangorelow Hello again! With the Android library you can use HTTP caching by creating an `HttpHandler` object with a file cache and then giving that handler to the `MapController` with `setHttpHandler`. An example of this is in our demo application: https://github.com/tangrams/tangram-es/blob/master/platforms/android/demo/src/main/java/com/mapzen/tangram/android/MainActivity.java#L84-L114

Does this answer your question?

**Comment by ivangorelow** [comment]
and is it possible to load map localy?

**Comment by tallytalwar** [comment]
Yes we added support for `mbtiles` in #1015. You will need to have the tile set in a [`mbtiles`](https://github.com/mapbox/mbtiles-spec) format.

Setting the scene file using the following syntax, you should be able to load the map using your `mbtiles` file.

```
sources:
    _savedTiles: #This is an example MBTiles data source.
        type: TopoJSON #We expect TopoJSON data from the source.
        url: /path/to/my/file.mbtiles #Only absolute file paths supported for now.
        max_zoom: 16 #Other optional parameters are applied as usual.
```

Let us know if this works for you.

**Comment by ivangorelow** [comment]
no, it doesn't workt

I have error `ERROR mbtilesDataSource.cpp:246: Unable to open SQLite database:`

**Comment by tallytalwar** [comment]
Thanks @ivangorelow 

Can you share the MBTiles file you are trying to open?

Thanks

**Comment by ivangorelow** [comment]
@tallytalwar  https://openmaptiles.os.zhdk.cloud.switch.ch/v3.3/extracts/moscow_russia.mbtiles

**Comment by tallytalwar** [comment]
Ok looks like we need to do resolve android asset path for sqlite database construction, which is not being done at present.

@ivangorelow what path are you putting the mbtiles file in? Are you bundling with the asset?

**Comment by JinYongwHwa** [comment]
I try offline tangram map by mbtiles

this is my scene file
```
sources:
    pinonmap:
        type: TopoJSON #GeoJSON, MVT, TopoJSON
        url: file:///storage/emulated/0/test/seoul.mbtiles
        max_zoom: 16
```

this is my test mbtiles file (1-10 zoom level seoul )
[seoul.zip](https://github.com/tangrams/tangram-es/files/815984/seoul.zip)

i have error too

mbtilesDataSource.cpp:246: Unable to open SQLite database: file:///storage/emulated/0/test/seoul4.mbtiles - unable to open database file


p.s
@matteblair Thank you very much to make this wonderful map

**Comment by ivangorelow** [comment]
@tallytalwar I try to bundle with asset. I try to do it with full path

**Comment by tallytalwar** [comment]
Yup,  was just confirming. I was able to reproduce this behavior. Will update when I have more information on this. 

Thanks again for the report.

**Comment by matteblair** [comment]
@JinYongwHwa @ivangorelow File access on Android can be a little complicated. Currently we can only load MBTiles files that are _not_ in the asset bundle for your application (because asset bundles are zip archives and not directories). You'll need to put your MBTiles file in your device storage and use the path to that file as the `url`, like `/storage/emulated/0/test/seoul.mbtiles` from the example above (I believe the `file://` scheme isn't used here). Finally, you need to make sure that your application has the correct permissions to read the file, most likely the [READ_EXTERNAL_STORAGE](https://developer.android.com/reference/android/Manifest.permission.html#READ_EXTERNAL_STORAGE) permission.

It's also possible that there's another problem, but try these steps first and let us know if you succeed!

**Comment by JinYongwHwa** [comment]
@matteblair thanks for your answer

I change schema
```
sources:
    pinonmap:
        type: TopoJSON #GeoJSON, MVT, TopoJSON
        url: /storage/emulated/0/test/seoul.mbtiles
        max_zoom: 16
``` 

then i find this error log 
```
ERROR mbtilesDataSource.cpp:246: Unable to open SQLite database: asset:///storage/emulated/0/test/seoul.mbtiles - unable to open database file
```
