### ISSUE TITLE
Directional arrows

### ISSUE THREAD

**Issue by sheikh-iffi** [tangrams/tangram-es#1313]
Hi guys

I am facing some issues regarding directional arrows. 

**1:** At some places, arrows are drawn at wrong places e.g. in the below image arrow is not drawn on road
![screenshot from 2017-02-23 12-46-28](https://cloud.githubusercontent.com/assets/12157369/23256760/b695fdaa-f9e2-11e6-9305-cb7f77f4ab20.png)

**2:** At some places arrows direction is wrong. e.g. in the below image you can see E Houston St to have arrows in both direction
![screenshot from 2017-02-23 12-55-15](https://cloud.githubusercontent.com/assets/12157369/23256858/0fd24536-f9e3-11e6-90b1-acdcd35ca029.png)

**3:** There is no consistency between placing distance. e.g. in the below image one road is filled with arrows and other with little or no arrows.
![screenshot from 2017-02-23 16-06-31](https://cloud.githubusercontent.com/assets/12157369/23256951/6275dbc2-f9e3-11e6-94f1-c03f897be809.png)

Thanks

**Comment by tallytalwar** [comment]
Can you share the scene file with us? And are you using our vector tile source?

Arrows are drawn based on the underlying geometry. My initial hunch is that the underlying polyline data could be incorrect. But can not be sure without looking at the scene file and referring the underlying vector tile data.

**Comment by sheikh-iffi** [comment]
I am using your scene file [scene.yaml](https://github.com/tangrams/tangram-es/blob/master/scenes/scene.yaml) without any changes.

**Comment by tallytalwar** [comment]
K will give this a look and update. Thanks

**Comment by tallytalwar** [comment]
So looked some more into this:

1. **Arrow not on road**
  It looks like we do have some issues with arrow placement and overzooming.
  At zoom < 18:
  ![screen shot 2017-03-02 at 10 23 57 am](https://cloud.githubusercontent.com/assets/360641/23513763/30d9bab6-ff33-11e6-8a61-e2d0fc92823c.png)
  At zoom > 18:
  ![screen shot 2017-03-02 at 10 24 06 am](https://cloud.githubusercontent.com/assets/360641/23513786/45e22e7a-ff33-11e6-9891-5fa196ccb504.png)
  This further needs investigation.

2. **arrows direction is wrong**
   I think this is due to underlying data. I checked on JS and it looks the same:
   ![screen shot 2017-03-02 at 10 26 06 am](https://cloud.githubusercontent.com/assets/360641/23515016/fc3c4216-ff36-11e6-84a3-2fc9aa4ccd0c.png)

3. **There is no consistency between placing distance**
   Once I modified the scene file to have different filtering and setting appropriate priority for arrow icons, these were consistent. Example:
    ![screen shot 2017-03-02 at 10 14 13 am](https://cloud.githubusercontent.com/assets/360641/23515062/24102334-ff37-11e6-8118-482ed15b42fd.png)


Will see what can be done for the "Arrow on road" issue, and update.

Thanks for this bug report.

**Comment by tallytalwar** [comment]
We resolved the issue with the arrow being shown outside roads, on overzooming (#1342). Other issues mentioned in the original issue description have already being addressed above in the comments, marking this resolved and closing.

Thanks

**Comment by sheikh-iffi** [comment]
Thanks
Issue regarding arrow being shown outside roads is solved now. But I still can't solve the issue about :
> There is no consistency between placing distance

Can you tell me what you did to fix it?
> Once I modified the scene file to have different filtering and setting appropriate priority for arrow icons, these were consistent

**Comment by tallytalwar** [comment]
@sheikh-iffi 

Can you try adding `priority: 0` to the arrows draw rule. So:

```
        arrows:
            # oneway arrows and shields are distinct groups!
            filter: { oneway: yes, shield_text: false, $zoom: { min: 17 } }
            draw:
                icons:
                    priority: 0
                    flat: true
                    sprite: arrow
                    size: [[17, 18px], [18, 20px], [20, 32px]]
                    placement: spaced
                    placement_spacing: [[17, 70px], [20, 175px]]
                    angle: auto
```
