### ISSUE TITLE
tangram-es vs. tangram styles

### ISSUE THREAD

**Issue by horvayev** [tangrams/tangram-es#1314]
Hello, I am rewriting [mapbox style](https://github.com/klokantech/mapbox-gl-js-offline-example) using tangramplay. I load same data using [tileserver-gl](https://github.com/klokantech/tileserver-gl). It works in tangram play, but text and lines are not displayed when I use the scene in android. Layers styles:

```yaml
country-glow-inner:
        data:
            source: mapzen
            layer: country
        draw:
            lines:
                color: [0.133, 0.4, 0.533, 0.8]
                width: 2px
                cap: round
```

and

```yaml
country-abbrev:
        data:
            source: mapzen
            layer: country-name
        filter:
            $zoom: { min: 2, max: 4 }
        draw:
            points:
                size: 2px
                color: red
                offset: [0px, -10px]
                text:
                    priority: 1
                    text_source: ABBREV
                    font:
                        size: 12px
                        fill: [0, 0, 0, .8]
                        stroke: { color: white, width: 2 }
                        transform: uppercase
                        weight: bold
                        size: [[3,10],[4,11],[5,12],[6,16]]
```

yaml file:

```yaml
scene:
    background:
        color: [0.866, 0.933, 1, 1]
styles:
    dashed-lines:
        base: lines
        dash: [6,2,2,2]
sources:
    mapzen:
        type: MVT
        url: /sdcard/Download/countries.mbtiles
layers:
    area-white:
        data:
            source: mapzen
            layer: country
        filter: { ADM0_A3: [ATA] }
        draw:
            polygons:
                order: 10
                color: [0.941, 0.972, 1, 1.00]
    area-red:
        data:
            source: mapzen
            layer: country
        filter: { ADM0_A3: [AFG,ALD,BEN,BLR,BWA,COK,COL,DNK,DOM,ERI,FIN,FRA,FRO,GIB,GNB,GNQ,GRC,GTM,JPN,KIR,LKA,MHL,MMR,MWI,NCL,OMN,RWA,SMR,SVK,SYR,TCD,TON,URY,WLF] }
        draw:
            polygons:
                order: 10
                color: [0.992, 0.686, 0.419, 1.00]
    area-orange:
        data:
            source: mapzen
            layer: country
        filter: { ADM0_A3: [AZE,BGD,CHL,CMR,CSI,DEU,DJI,GUY,HUN,IOA,JAM,LBN,LBY,LSO,MDG,MKD,MNG,MRT,NIU,NZL,PCN,PYF,SAU,SHN,STP,TTO,UGA,UZB,ZMB] }
        draw:
            polygons:
                order: 10
                color: [0.992, 0.776, 0.388, 1.00]
    area-yellow:
        data:
            source: mapzen
            layer: country
        filter: { ADM0_A3: [AGO,ASM,ATF,BDI,BFA,BGR,BLZ,BRA,CHN,CRI,ESP,HKG,HRV,IDN,IRN,ISR,KNA,LBR,LCA,MAC,MUS,NOR,PLW,POL,PRI,SDN,TUN,UMI,USA,USG,VIR,VUT] }
        draw:
            polygons:
                order: 10
                color: [0.980, 0.890, 0.392, 1.00]
    area-green:
        data:
            source: mapzen
            layer: country
        filter: { ADM0_A3: [ARE,ARG,BHS,CIV,CLP,DMA,ETH,GAB,GRD,GRL,HMD,IND,IOT,IRL,IRQ,ITA,KOS,LUX,MEX,NAM,NER,PHL,PRT,RUS,SEN,SUR,TZA,VAT] }
        draw:
            polygons:
                order: 10
                color: [0.827, 0.894, 0.435, 1.00]
    area-turquoise:
        data:
            source: mapzen
            layer: country
        filter: { ADM0_A3: [AUT,BEL,BHR,BMU,BRB,CYN,DZA,EST,FLK,GMB,GUM,HND,JEY,KGZ,LIE,MAF,MDA,NGA,NRU,SLB,SOL,SRB,SWZ,THA,TUR,VEN,VGB] }
        draw:
            polygons:
                order: 10
                color: [0.666, 0.858, 0.470, 1.00]
    area-blue:
        data:
            source: mapzen
            layer: country
        filter: { ADM0_A3: [AIA,BIH,BLM,BRN,CAF,CHE,COM,CPV,CUB,ECU,ESB,FSM,GAZ,GBR,GEO,KEN,LTU,MAR,MCO,MDV,NFK,NPL,PNG,PRY,QAT,SLE,SPM,SYC,TCA,TKM,TLS,VNM,WEB,WSB,YEM,ZWE] }
        draw:
            polygons:
                order: 10
                color: [0.639, 0.807, 0.772, 1.00]
    area-purple:
        data:
            source: mapzen
            layer: country
        filter: { ADM0_A3: [ABW,ALB,AND,ATC,BOL,COD,CUW,CYM,CYP,EGY,FJI,GGY,IMN,KAB,KAZ,KWT,LAO,MLI,MNP,MSR,MYS,NIC,NLD,PAK,PAN,PRK,ROU,SGS,SVN,SWE,TGO,TWN,VCT,ZAF] }
        draw:
            polygons:
                order: 10
                color: [0.807, 0.709, 0.811, 1.00]
    area-pink:
        data:
            source: mapzen
            layer: country
        filter: { ADM0_A3: [ARM,ATG,AUS,BTN,CAN,COG,CZE,GHA,GIN,HTI,ISL,JOR,KHM,KOR,LVA,MLT,MNE,MOZ,PER,SAH,SGP,SLV,SOM,TJK,TUV,UKR,WSM] }
        draw:
            polygons:
                order: 10
                color: [0.952, 0.756, 0.827, 1.00]
    land-border-country:
        data:
            source: mapzen
        draw:
            lines:
                order: 50
                color: [1, 1, 1, 1]
                width: 1.5px
    country-glow-inner:
        data:
            source: mapzen
            layer: country
        draw:
            lines:
                color: [0.133, 0.4, 0.533, 0.8]
                width: 2px
                cap: round
    state:
        data:
            source: mapzen
        filter:
            ADM0_A3: [USA,CAN,AUS]
            $zoom: { min: 4 }
        draw:
            dashed-lines:
                color: [0.133, 0.4, 0.533, 0.25]
                width: 1.2px
    country-abbrev:
        data:
            source: mapzen
            layer: country-name
        filter:
            $zoom: { min: 2, max: 4 }
        draw:
            points:
                size: 2px
                color: red
                offset: [0px, -10px]
                text:
                    priority: 1
                    text_source: ABBREV
                    font:
                        size: 12px
                        fill: [0, 0, 0, .8]
                        stroke: { color: white, width: 2 }
                        transform: uppercase
                        weight: bold
                        size: [[3,10],[4,11],[5,12],[6,16]]
    country-name:
        data:
            source: mapzen
            layer: country-name
        filter:
            $zoom: { min: 4 }
        draw:
            points:
                size: 0px
                color: red
                offset: [0px, -10px]
                text:
                    priority: 1
                    text_source: NAME
                    font:
                        size: 12px
                        fill: [0, 0, 0, .8]
                        stroke: { color: white, width: 2 }
                        transform: uppercase
                        weight: bold
                        size: [[3,10],[4,11],[5,12],[6,16]]
```

I tried to specify font loaded from internet or local. Still withot success.

**Comment by horvayev** [comment]
ok, so the problem was in identation. I didn't know I can't use tabs. It works now.

**Comment by hjanetzek** [comment]
hey -- could you share the scene file that did not work? Tabs should be ok just some mixes of tabs and spaces in the indentation are problematic (in strict yaml)

**Comment by horvayev** [comment]
I have been playing with it a little bit more. I just realized that on linux and android i have to specify fonts in order. This was the problem.  Bad identation just resulted in black screen. I do not have original file, but [current scene](http://pastebin.com/7v1RHEDu) is still not working on 100%. Layer (should display blue line between water and country)
```yaml
 country-glow-inner:
        data:
            source: mapzen
            layer: country
        draw:
            lines:
                color: [0.133, 0.4, 0.533, 0.8]
                width: 2px
                cap: round
```
doesn't work on on adnroid/linux but works in tangram play.

Linux:
![tangramlinux](https://cloud.githubusercontent.com/assets/4464147/23267788/146eb468-f9ec-11e6-8244-49c0d96ca688.png)

Tangramplay:
![tangramplay](https://cloud.githubusercontent.com/assets/4464147/23267795/1c5de9aa-f9ec-11e6-8e04-67a99b143a39.png)
