### ISSUE TITLE
Node images become invisible on certain zoom levels

### ISSUE THREAD

**Issue by westnordost** [tangrams/tangram-es#1415]
Here is one difficult to reproduce bug, I think. [I got this bug report in StreetComplete](https://github.com/westnordost/StreetComplete/issues/50).

**In a nutshell:** Images for nodes (with collision on) turn invisible on certain zoom levels even though there doesn't seem to be anything in the way that would warrant a collision.

https://files.natenom.com/public/cs/a_1.png
https://files.natenom.com/public/cs/a_2.png
(More images and GPS positions in the linked ticket)

The markers in this app are just another data layer, their theme is declared here:
https://github.com/westnordost/StreetComplete/blob/master/app/src/main/assets/streetcomplete.yaml

The reporter uses a Samsung Galaxy S5. I cannot reproduce it with a Sony Xperia Z1 Compact, Android 5.1.1

**Comment by westnordost** [comment]
The user had the courtesy to make a screencast to better illustrate the problem:

https://files.natenom.com/public/cs/cs.mp4

**Comment by westnordost** [comment]
Hmm, I am getting feedback from quite a few users that they have the same problem as the original bug reporter. Here is the link of the original ticket again: https://github.com/westnordost/StreetComplete/issues/50

Do you acknowledge that this is a bug in tangram-es?

**Comment by matteblair** [comment]
Hi @westnordost, I'll take a closer look at this. Which version(s) of tangram-es are you seeing this with, and on what devices?

**Comment by hjanetzek** [comment]
Have you tried to set the quest-icons priority to zero so that they don't get blocked by other labels?

**Comment by westnordost** [comment]
@matteblair Hmm, I think I get this independent of the device

@hjanetzek Oh, no, I haven't used the `priority` at all yet. I also just read this note in the docs

> [[JS only] Only points and text elements from the same datasource will collide with each other, so priority values only apply within a single datasource.](https://mapzen.com/documentation/tangram/draw/#priority)

I will try this and report back.

**Comment by tallytalwar** [comment]
@westnordost just tried building StreetComplete with `priority: 0` set for the `streetcomplete_quest` layer. Seems to give much better results, as the the quest icons are not colliding with other street labels.

```yaml
streetcomplete_quests:
        filter: { $zoom: { min: 14 } }
        data: { source: streetcomplete_quests }
        draw:
            quest-icons:
                interactive: true
                priority: 0
                size: 64px
                sprite: function() { return feature.kind }
                sprite_default: quest
                offset: [-16px, -64px]
```
