### ISSUE TITLE
libtangram.so error

### ISSUE THREAD

**Issue by JunsuLime** [tangrams/tangram-es#1540]
#00 pc 0000000000224764  /data/app/com.test.map-2/lib/arm64/libtangram.so (_ZN7Tangram15DynamicQuadMeshINS_12SpriteVertexEE4drawERNS_11RenderStateERNS_13ShaderProgramEib+148)
#01 pc 00000000002246a0  /data/app/com.test.map-2/lib/arm64/libtangram.so (_ZN7Tangram10PointStyle16onBeginDrawFrameERNS_11RenderStateERKNS_4ViewERNS_5SceneE+120)
#02 pc 00000000001756f4  /data/app/com.test.map-2/lib/arm64/libtangram.so (_ZN7Tangram3Map6renderEv+896)
#03 pc 0000000000a19d14  /data/app/com.test.map-2/oat/arm64/base.odex (offset 0x960000)

I execute method that

1) remove marker and draw marker
2) using mapController, set position, zoom, tilt, rotation
3) marker.setVisible(bool)

one method contains 1,2,3 step all.

And error message above is sended.

My Tangram version is 0.7.1 and device OS version is 7.1.1, device: Nexus 5X and other device such as SAMSUNG edge 6s, Nexus 6P and other device have same problem.

This problem does not happen every time, but often come up.

**Comment by hjanetzek** [comment]
Hi @JunsuLime thanks for the report!  Can you share the snippet for the function that triggers the crash? What do you mean by 'remove and draw marker' exactly?

**Comment by JunsuLime** [comment]
case1)

// At this code, error happened.
```java
mapController.removeMarker(selectedMarker)

for (Marker marker : myPinMarkers) {
  if (marker.isVisible()) marker.setVisible(false);
}

for (Marker marker : otherPinMarkers) {
  mapController.removeMarker(marker);
} 

for (Pin pin : trip.getPins()) {
  Marker marker = getMarker(U.SELECT_STATUS_OTHER_PIN);
  marker.setPoint(new LngLat(pin.getLng(), pin.getLat()));
  otherPinMarkers.add(marker);
}
```

```java
public Marker getMarker(int status) {
   marker = mapController.addMarker();
   marker.setStylingFromString(U.clickEffectStyle);
   marker.setDrawable(U.selectedCircleDrawable);
   marker.setDrawOrder(0);
   return marker;
}
```


case2)

// At this code, error happened.
```java
// this code's input lngLat is come from gps location
// and I converted location -> LngLat
// and Location granted NonNull
setMapPosition(lngLat, false);
drawMyLocation(lngLat);
```

```java
public void setMapPosition(LngLat lngLat, boolean forceNoEase) {
  if (isSoFar(lngLat) || forceNoEase)
    mapController.setPosition(lngLat);
  else 
    mapController.setPosition(lngLat, MOVE_EASE_TIME);
}
```

```java
public boolean isSoFar(LngLat targetPosition) {

    PointF pinPoint = mapController.lngLatToScreenPosition(targetPosition);
    double distanceDp = Math.sqrt((pinPoint.x - SCREEN_CENTER_X) * (pinPoint.x - SCREEN_CENTER_X)
            + (pinPoint.y - SCREEN_CENTER_Y) * (pinPoint.y - SCREEN_CENTER_Y));

    double screenOverTime = distanceDp / NO_EASE_LENGTH;

    if (screenOverTime * mapController.getZoom() < EASE_LIMIT) return false;
    else return true; 
}
```

```java
// myLocationMarker is class member variable
public void drawMylocation(LngLat location) {
    if (mapController == null) {
        return;
    }
    mapController.removeMarker(myLocationMarker);

    myLocationMarker = mapController.addMarker();
    myLocationMarker.setDrawable(R.drawable.dot_glow);
    myLocationMarker.setStylingFromString(U.myLocationStyle);
    myLocationMarker.setPoint(new LngLat(location.longitude, location.latitude));
}
```

This error does not happened at every case. But sometime It works not well and throw this error and application quited.

**Comment by JunsuLime** [comment]
In My Application. Google Developer console Android vital logs..

This Backtrace is printed. I appened this backtrace to hope you are helped by this log

## log1)
```
backtrace:
  native: pc 0000000000224764  /data/app/com.test.map-2/lib/arm64/libtangram.so (_ZN7Tangram15DynamicQuadMeshINS_12SpriteVertexEE4drawERNS_11RenderStateERNS_13ShaderProgramEib+148)
  native: pc 00000000002246a0  /data/app/com.test.map-2/lib/arm64/libtangram.so (_ZN7Tangram10PointStyle16onBeginDrawFrameERNS_11RenderStateERKNS_4ViewERNS_5SceneE+120)
  native: pc 00000000001756f4  /data/app/com.test.map-2/lib/arm64/libtangram.so (_ZN7Tangram3Map6renderEv+896)
  native: pc 0000000000c762c4  /data/app/com.test.map-2/oat/arm64/base.odex
```

## log2)
```
backtrace:
  native: pc 000000000012e6b4  /data/app/com.pinonmap.map-1/lib/arm64/libtangram.so (Java_com_mapzen_tangram_MapController_nativeDispose+32)
  native: pc 0000000000a1ac34  /data/app/com.pinonmap.map-1/oat/arm64/base.odex
```

I think that this case does not happen always so hard to debug. 

Thanks for your help @hjanetzek . 
At your debugging, I will do my best to help you to correct this error.
