### ISSUE TITLE
Can't see data from mbtiles in Android

### ISSUE THREAD

**Issue by rwrx** [tangrams/tangram-es#1544]
I am trying to use mbtiles file as in this issue: https://github.com/tangrams/tangram-es/issues/1309 . But I am not able to see anything on map. I am using this mbtiles source file from that issue: https://openmaptiles.os.zhdk.cloud.switch.ch/v3.3/extracts/moscow_russia.mbtiles . And also this scene.yaml file: https://gist.github.com/rwrx/8f3e72615fc629edff40fa0e749715f6 . It has sources defined as:

```
osm:
        type: MVT
        url: file:///storage/emulated/0/moscow_russia.mbtiles
        max_zoom: 16
```

In Tangram-ES in Android I have enable LOG_LEVEL 3 and I can see this log message: 

`mbtilesDataSource.cpp:251: SQLite database opened: /storage/emulated/0/moscow_russia.mbtiles`

and also this kind of messages:

`mbtilesDataSource.cpp:159: loaded tile: 308/159/9/9, 31840`

But on map I see nothing. I am on Moscow coordinates but nothing is showing. Are mbtiles files supposed to work correctly on Android? Or which kind of mbtiles do I need? Thank you a lot.
