### ISSUE TITLE
Tried to load scenePath twice

### ISSUE THREAD

**Issue by MyZeD** [tangrams/tangram-es#1593]
Hello,

 I use to compile tangram-es the default cmake file on Arch-Linux (+clang 4.0.1) about my self cmake with "add_subdirectory".
All compiles fine in Version 0.7.1 (just using this Version) - because i don't be able to compile the Version 0.7.2 yet :/

The Problem:
If I loaded tangram in my client with:

Map.linux.cpp:
```
[...]
map = new Tangram::Map(platform);
map->loadSceneAsync("Resources/map/scene.yaml", false, {}, nullptr, {});
[...]
```

scene.yaml:
```
[...]
textures:
    pois:
        url: img/poi_icons_32.png                <----
        sprites:
            plane: [0, 0, 32, 32]
[...]
```

(with **url: ./img/poi_icons_32.png** i get the self result)

The Result is in Terminal:
```
[...]
WARNING platform.cpp:29: Failed to read file at path: Resources/map/Resources/map/img/poi_icons_32.png
ERROR sceneLoader.cpp:646: Can't load texture resource at url 'Resources/map/Resources/map/img/poi_icons_32.png'
ERROR sceneLoader.cpp:699: Missing texture pois
[...]
```

How you see, tangram-es tries to load the "/map/Resources" twice.
Is it a bug in 0.7.1 and already clean?

Thank you for reply  :+1:
