### ISSUE TITLE
Texts are broken with buffered tiles

### ISSUE THREAD

**Issue by jaakla** [tangrams/tangram-es#1674]
1. Use vector tiles which have buffer, e.g. OpenMapTiles or Mapbox mbstreets. 
2. Try to render texts
3. You'll see that texts which are in buffer (outside tile borders) are rendered in seemingly random places outside tiles (maybe tile center?). We see even country names here far away from the real object borders ("Eesti"=Estonia is in Lithuania and Belarus).

**RESULT:**

![screen shot 2017-10-03 at 11 51 56](https://user-images.githubusercontent.com/5609650/31117575-fda883f8-a832-11e7-87d6-c7a13f77b6d3.jpg)

**EXPECTED RESULT:**

No wrong placement and duplicated texts.

**ENVIRONMENT:**
Tangram Play, CARTO vector tiles with OpenMapTiles schema and buffers. See yml in screenshot.

Data source:
```yml
sources:
    carto:
        type: MVT
        url: https://cartobase-1.global.ssl.fastly.net/vectortiles/carto.streets/v1/{z}/{x}/{y}.mvt
        max_zoom: 14
```

**OTHER:**
Tried varying _buffer:_ parameter for texts, it affects texts renderings, but does not fix or even improve it really.

Same issue was also mentioned in comment of #1580 and commented by @nvkelso . Added this here as separate issue, as it makes base map rendering with Tangram and none-mapzen tiles impossible in practise.

**Comment by nvkelso** [comment]
I agree this is a separate issue than #1580, thanks for filing!

**Comment by bcamper** [comment]
Thanks - it looks like this specific issue references JS/Tangram Play, so would be better to track as a Tangram JS issue under https://github.com/tangrams/tangram.

That said, what geometry type is in the `places` you are labelling? Labels applied to polygons will render in the polygon centroid, which (unfortunately) for tiled data, often means... the center of the tile. We generate explicit point geometries for labelling where necessary in Mapzen tiles. Is this possibly happening here, or have I misunderstood?

Is the rendering substantially different if `buffer: 0px`, or when rendering the same data on non-buffered tiles?

**Comment by nvkelso** [comment]
It'd also be helpful to see your YAML file, or at least your sources block and the places block drawing those text labels.

**Comment by nvkelso** [comment]
Closing in favor of https://github.com/tangrams/tangram/issues/602.

**Comment by jaakla** [comment]
The geometry is Point, not polygon. I think the Point is in different tiles, but in one of them it is within bounds (0..4096 pix), but in the others it is probably repeated in the "outside buffer", i.e. with coordinates <0 or >4096. As result Tangram seems to try to render somewhere within that tile, maybe center, but always in some very wrong location.

Changing buffer from 0px looks quite different, but still very wrong. See video: https://drive.google.com/file/d/0B3Rm1qU6KnySVW9lWFZPR1ExRXc/view?usp=sharing

The YAML:

```yaml
sources:
    carto:
        type: MVT
        url: https://cartobase-1.global.ssl.fastly.net/vectortiles/carto.streets/v1/{z}/{x}/{y}.mvt
        max_zoom: 14
place:
        data: { source: carto}
        filter: {class: country, $zoom: {min: 3}}
        draw:
            text-blend-order:
                priority: 1
                text_source: name
                buffer: 1px
                font:
                    size: [[13, 9px], [14, 10px], [15, 11px], [16, 12px], [17, 13px]]
                    fill: global.med_text
                    family: Montserrat
                    weight: normal
                    stroke: { color: global.minor_halo, width: 2 }
```
