### ISSUE TITLE
Set styling for ClientGeoJsonSource polyline

### ISSUE THREAD

**Issue by rwrx** [tangrams/tangram-es#1684]
Hello, in this issue #1655 I was advised to use `ClientGeoJsonSource` instead of `Marker` interface for showing polylines correctly. Unfortunately my app is already in production and many users have problems with displaying polylines when they are long. So I have decided to use `ClientGeoJsonSource` and now I need to set styling for these polylines. I can see that functionality for adding `ClientGeoJsonSource` is exposed by `MapzenMap.addPolyline()`. As I have digged deeper I have discovered that `OverlayManager.addPolylineToPolylineMapData()` has option to set properties, but I don't know how to use it correctly. I have tried hardcoding this for example but color for line does not changed:

```
private MapData addPolylineToPolylineMapData(List<LngLat> coordinates) {
  HashMap<String, String> properties = new HashMap<String, String>();
  properties.put("color",  "[1.0, 1.0, 0.0, 1.0]");
  MapData mapData = polylineMapData.addPolyline(coordinates, properties);
  mapController.requestRender();
  return mapData;
}
```

Could I ask you to provide me some information how to correctly style `ClientGeoJsonSource` polyline through code? Thank you a lot.

**Comment by tallytalwar** [comment]
Hi @rwrx 

`properties` for a `MapData` append to the properties of the tiled feature and has no direct affect on the rendering style.

To style a clientDataSource one would have to define apt draw group in the scene file. As an example refer [this](https://github.com/tangrams/bubble-wrap/blob/gh-pages/bubble-wrap-style.yaml#L805-L815) block in our bubble-wrap style.
```yaml
    mz_route_line_transit:
        data: { source: mz_route_line_transit }
        draw:
            ux-transit-line-overlay:
                # each transit route segment could be a different "line" each with it's own color
                # but some transit lines don't define a color, in those cases default to blue
                # and since the color is coming from Transit.land they call it "color" instead of "colour"
                interactive: global.sdk_interactive
                color: function() { return feature.color || '#06a6d4'; }
                order: 500
                width: [[0,3.5px],[5,5px],[9,7px],[10,6px],[11,6px],[13,8px],[14,9px],[15,10px],[16,11px],[17,12px],[18,10px]]
```
Here all features added do the `mz_route_line_transit` client data source (from mapzen android or ios sdk), will be drawn with the style parameters in the draw group.

Similar to this you will have to define a styling `layer` which will use the clientdatasource name you are adding in the `data` yaml block.

With respect to using client data source properties, you can refer [this](https://github.com/tangrams/bubble-wrap/blob/gh-pages/bubble-wrap-style.yaml#L865-L879) block.
```yaml
    mz_search_result:
        data: { source: mz_search_result }
        draw:
            ux-icons-overlay:
                interactive: global.sdk_interactive
                sprite: ux-search-active
                size: [36px,54px]
                collide: false
                anchor: top
                transition: { show: { time: 0s }, hide: { time: 0s } }
        inactive:
            filter: { state: inactive }
            draw:
                ux-icons-overlay:
                    sprite: ux-search-inactive
```
Here the `state` property is [set in mapzen sdk](https://github.com/mapzen/android/blob/11b7aa653a73e3059bd102fbf6e89a39d8ee8800/core/src/main/java/com/mapzen/android/graphics/OverlayManager.java#L504) which can then be used to filter features for different styling.

Closing this issue, please reopen if you still have more questions on this.

Thanks
