### ISSUE TITLE
Cannot render MBTiles on Android

### ISSUE THREAD

**Issue by matteblair** [tangrams/tangram-es#1714]
@saeedtabrizi says:

@matteblair , @Buthrakaur , I have same issue on Android .
i can't render via following scene configuration 👍
```
osm_offline1:
        type: MVT
        url: /storage/emulated/0/demo.mbtiles
        max_zoom: 14  
```
or there is a undocumented feature or configuration to load and render .mbtiles in android .
Please write a sample here
Thanks .

**Comment by matteblair** [comment]
Hi! Thanks for your the feedback on the MBTiles feature. To help resolve your issue, I'll need the version of Tangram ES that you're using and the logcat output of Tangram ES when you encounter the issue.

**Comment by saeedtabrizi** [comment]
Hi @matteblair , 
I'm using  the latest cloned version  and compiled at the yesterday .
Now i confirm that I can use the **offline** `.mbtiles` in my android device and it's **OK** for rendering map with my custom **scene** file . 
```
sources:
    osm_offline:
        type: MVT
        url: file:///storage/emulated/0/demo.mbtiles
        max_zoom: 14
```
So i want to know, how  can i switch between the sources in runtime with a global variable :
```
global:
    feature_order: function () { return feature.sort_rank; }
    osm_source: 'osm_offline'
    scene_background_color: '#f0ebeb'
sources:
    osm_offline:
        type: MVT
        url: file:///storage/emulated/0/demo.mbtiles
        max_zoom: 14
    osm_online:
        type: MVT
        url: https://tile.mapzen.com/mapzen/vector/v1/all/{z}/{x}/{y}.mvt
        max_zoom: 16
        url_params:
            api_key: "mapzen-anycodehere"
        cache:  file:///storage/emulated/0/cache.mbtiles
    osm_source: function() { return sources[global.osm_source] ;  } 
```
The above lines returns **error** in parsing scene file exactly . 
Can i have similar functionality in the scene files ? how ? 
Thanks.

**Comment by matteblair** [comment]
Hey thanks for the reminder about Android file access permissions, I've added a note about that to the proposed documentation changes.

To switch between using the two data sources in your example, I think the best way is to set up your scene like this:
```yaml
global:
  ...
  osm_source: osm_online
sources:
  osm_online:
    ...
  osm_offline:
    ...
layers:
  earth:
    data: { source: global.osm_source }
    ...
```
And then to change `global.osm_source` when you want to switch between the online and offline source. 

The `function()` syntax does not apply to all parts of the scene file, only styling parameters in the `layers` section.

Let me know if this helps or if you have more questions!
