### ISSUE TITLE
Raster Source with single file GeoJSON mask not requesting any tiles

### ISSUE THREAD

**Issue by ac87** [tangrams/tangram-es#1754]
I am revisiting my solution to rendering KML Image overlays #866 

With the current 0.9.1 snapshot when the overlay's source GeoJSON is for a single file (not tiled) no tiles are requested.

```
styles:
    raster-blended:
        base: raster
        blend: overlay

sources:
    image-overlay-rasters: { type: Raster, url: 'http://localhost:8888/{x}/{y}/{z}.overlay.png' }
    image-overlay-source:
        type: GeoJSON
        url: image_overlay.json
        rasters: [image-overlay-rasters] # attach image layer

layers:
    overlay-image:
        data: { source:  image-overlay-source }
        draw:
            raster-blended:
                order: 220
```

If I modify it so the web server serves the same GeoJSON repeatedly as tiles i.e. `url: http://localhost:8888/{x}/{y}/{z}/image_overlay.json` the tiles get loaded (although actually it looks more like the map just requests every tile possible)

To add: the tiles get loaded, masked to the correct area from the GeoJSON, but the bitmap distorts like crazy.
