### ISSUE TITLE
[Android] Adding polygons/polylines with style

### ISSUE THREAD

**Issue by dgngulcan** [tangrams/tangram-es#1775]
I am creating a `MapData` with a style name that is in `yaml` file and adding my polygons to that layer.

**Scenario**
I want to add several `Polygon`s with different styles to the map and then remove some of them later on.

**Issue 1:** When I create a DataLayer with a name that does not exist in the yaml file, polygons are not being added. e.g.
```kotlin
val polygonLayer = addDataLayer("mz_default_polygon");  // adding polygon to this layer works
val polygonLayer = addDataLayer("some_string"); // adding polygon to this layer does not work 
```

**Issue 2:** When I pass my properties to `addFeature` function inside the `MapController`, they do not apply the style.

**Issue 3:** `Polygons` are overlapping the `Marker` even though it has less `order` index.
```
// marker's style
{ style: 'points', anchor: top, size: [50px, 50px], order: 2000, interactive: true, collide: false }

// polygon's style in yaml file
 mz_default_polygon:
        data: { source: mz_default_polygon }
        draw:
            sdk-polygon-overlay:
                interactive: global.sdk_interactive
                color: '#20dc3983'
                order: 500

            sdk-line-overlay:
                color: '#dc3983'
                cap: round
                order: 501
                width: 3px
```

**Issue 3:** I need to add multiple polygons and remove them distinctly from each other. To do so, I need to create different `MapData`s that has unique id's so I when I remove them, not all of them are removed since a `MapData` has one unique id. When I pass random ID to `addFeature` instead of layer id, it does not draw at all.

```kotlin

// adding a data layer
val polygonLayer = addDataLayer("mz_default_polygon");  

...

// adding a feature
 mapController.addFeature(polygonLayer.id,
                polygon.getCoordinates(),
                polygon.rings,
                polygon.getProperties());


...

val properties by lazy {
        val props = HashMap<String, String>()
        props["type"] = "polygons"
        props["order"] = "500"

        val out = arrayOfNulls<String>(props.size * 2)
        var i = 0
        for ((key, value) in props) {
            out[i++] = key
            out[i++] = value
        }
        out
    }

```

It looks like I am missing something. How can I add polygon and polyline properly?
