### ISSUE TITLE
Cannot set dash_background_color for line outline

### ISSUE THREAD

**Issue by rwrx** [tangrams/tangram-es#1834]
I tried to style railway as classic dashed line with dark colored outline. I came with this styling (only important parts are included):

```
globals:
...
    rail_primary_color: '#777'
    rail_secondary_color: '#fff'

...

styles:
...
    railway_dash:
    base: lines
    dash: [4.0, 4.0]
    dash_background_color: global.rail_secondary_color

...

layers:
...
    roads:
...
        railway:
        filter: { kind: rail }
        draw:
            lines:
                color: global.rail_primary_color
                width: [[10, 0px], [15, 1px], [17, 1px], [18, 3px]]
                outline:
                    width: 0
        rail:
            filter: { kind_detail: rail }
            draw:
                lines:
                    style: railway_dash
                    dash_background_color: global.rail_secondary_color
                    order: global.feature_order
                    outline:
                        color: red
                        dash_background_color: red
                        width: [[15, 0px], [18, 1px]]
                        order: 354
        tunnel:
            filter: { is_tunnel: true }
            draw:
                lines:
                    color: global.rail_tunnel_color
```

I have set red color for outline to be visible that on Tangram ES dash_background_color override for outline is ignored and it takes dash_background_color from lines. On Tangram JS this is working properly. I have also tried to outline to set dash: false and dash: [1.0, 0], but with the same result. I am attaching screenshots.

Screenshot from Tangram JS:
![tangram-js](https://user-images.githubusercontent.com/2378743/42408209-3eb4231e-81c9-11e8-99d9-906b90827a26.png)

Screenshot from Tangram ES:
![tangram-es](https://user-images.githubusercontent.com/2378743/42408233-a4e7c9e2-81c9-11e8-8e6d-ec3260089a33.png)
