### ISSUE TITLE
how to draw marker above text

### ISSUE THREAD

**Issue by shmulikMoradoff** [tangrams/tangram-es#1893]
Hi,
i am trying to kae my markers to be drown above text layers.
as far as i could see, text layers can't be ordered. so how can i make it be shown beneath the Markers?
here is how it looks like:

![markerbelowtext2](https://user-images.githubusercontent.com/13149164/46594814-ff068280-cadd-11e8-942b-6a1fa180714a.png)

example: 
text in yaml:
```
place_label_city:
    filter:
      $zoom:
        max: 16
      all:
        - $geometry: point
        - class: city
    data:
      source: openmaptiles
      layer: place
    draw:
      text:
        font:
          fill: 'hsl(0, 0%, 0%)'
          stroke:
            color: 'hsla(0, 0%, 100%, 0.75)'
            width: 2
          family:
            - Noto Sans Regular
          size:
            - - 3
              - 12
            - - 8
              - 16
        text_source: global.text_name
        text_wrap: 10
```
my markers are set in code to have:

style: points
order: 10000
flat: false
collide: false

i have also tried to put them both at  blend: inlay and use the blend_order, 
and tried to put the text at  blend: inlay and the Marker at overlay, but it did not work as well..
Thanks
