### ISSUE TITLE
Tiles are downloaded from sources in layers that are disabled.

### ISSUE THREAD

**Issue by polar** [tangrams/tangram-es#1973]
I have a situation where I have a disabled layer, or disabled a layer during a scene update, and the layer's data source tiles are getting downloaded. 

For example a Scene containing:

```
layers:
  weather_radar:
    data: { source: WeatherRadar }
    enabled: false
sources:
  WeatherRadar:
    type: 'Raster'
    url: 'https://tiles.com/weatherimage?x={x}&y={y}&z={z}'
    tile_size: 256
```
results in calls to ```'https://tiles.com/weatherimage``` for tiles.

It is expected to not make any calls as the source is exclusive to that layer.
