### ISSUE TITLE
Support custom attributes in style configuration

### ISSUE THREAD

**Issue by matteblair** [tangrams/tangram-es#2124]
In a `style` declaration, the `shaders` block can now contain a new entry called `attributes` -  a mapping of names to properties of custom vertex attributes. Those new attributes are given values in `draw` groups by assigning a value to the attribute's name in a new `attributes` block. All together, the new syntax looks like this:
```
buildings:
  base: polygons
  shaders:
    attributes:
      height:
        type: float
    blocks:
      color: |
        // Use the custom attribute's varying to shade by height
        color.rgb = vec3(min(height / 100., 1.), 0., 0.);
  draw:
    # use default draw parameters to set the height attribute value from the height feature property
    attributes:
      height: function() { return feature.height; }
```

The feature is fully described in the Tangram JS PR: https://github.com/tangrams/tangram/pull/739
