### ISSUE TITLE
Sprites in MapData layer are clipped too soon when they have a large offset

### ISSUE THREAD

**Issue by westnordost** [tangrams/tangram-es#2140]
**Tangram-ES Version**: 0.12

I have a MapData layer that contains large (~64x64px) pins on the map. These sprites have a large vertical offset that move their center to the bottom of the sprite. 
Some users report that sprites are clipped already while still being partly visible on the screen.

**Style used**
```
layers:
    streetcomplete_quests:
        data: { source: streetcomplete_quests }
        pins:
            filter: { $zoom: { min: 14 } }
            draw:
                quest-icons:
                    interactive: true
                    priority: function() { return feature.order }
                    size: 66px
                    sprite: function() { return feature.kind }
                    sprite_default: quest
                    offset: [-17px, -66px]
```
