### ISSUE TITLE
dash_background_color inconsistency with Tangram

### ISSUE THREAD

**Issue by rwrx** [tangrams/tangram-es#2150]
I have noticed that there is still problem with color transparency in Tangram ES. In Tangram, it was discussed in issue #741 and it is fixed now in v0.20.1.

In our use case: the first color track_background_color is set as transparent. The second color track_color is not transparent, this color is used in style dashed_grade5 as dash_background_color.

Our style with parameters below works in Tangram, but in Tangram ES our style with same parameters looks different: one can see two-colored dashed lines.

I am attaching a style: 
```

global:
    ...
    track_background_color: [1.0, 1.0, 1.0, 0.3]
    track_color: [0.6, 0.4, 0.0]
    ...
   
styles:
    ...
    dashed_grade5:
        base: lines
        blend: translucent
        dash: [1.5, 2.5]
        dash_background_color: global.track_color
        material:
            diffuse: 1.0
            ambient: 1.0
    ...
   
layers:
    ...
    roads:
        ...
        grade5:
            filter: { tracktype: grade5 }
            draw:
                lines:
                    style: dashed_grade5
                    color: global.track_background_color
                    width: [ [13, 1px], [16, 3px]]
                    visible: true
                    outline:
                        color: global.track_background_color
                        dash_background_color: global.track_background_color
                        width: 5px
```

And here is screenshot of this style in Tangram ES:

![tes](https://user-images.githubusercontent.com/2378743/75197774-5357e400-575f-11ea-9196-3d4b29e7a835.png)

And here is screenshot of this style in Tangram:

![t](https://user-images.githubusercontent.com/2378743/75197790-5c48b580-575f-11ea-94c8-a1153a1819bd.png)
