### ISSUE TITLE
use osm tiles instead of mapzen

### ISSUE THREAD

**Issue by liodali** [tangrams/tangram-es#2268]
i want to use tiles of osm mapnik in ios sdk
how i can load them or configure my scene.yaml to load them ?
here scene that i used to show osm tiles:
```yaml
sources:
  mapzen-osm:
    type: Raster
    url:  https://tile.openstreetmap.org/{z}/{x}/{y}.png
    tile_size : 256
    max_zoom: 16

```

**Comment by matteblair** [comment]
Hello! Your tile source configuration looks correct to me. You also need a layer to draw the raster tiles in your scene file, like this:
```yaml
layers:
  osm-raster:
    data:
      source: mapzen-osm
    draw:
      raster:
        order: 0 # draw on bottom
```

The same scene file will work on any supported Tangram platform, including iOS.

**Comment by liodali** [comment]
thanks i will test it 
and for adding polyline  do i need to add style for them in my file configuration

**Comment by liodali** [comment]
when create yaml file that contain 
```
sources:
  mapzen-osm:
    type: Raster
    url:  https://tile.openstreetmap.org/{z}/{x}/{y}.png
    tile_size : 256
    max_zoom: 16

layers:
  osm-raster:
    data:
      source: mapzen-osm
    draw:
      raster:
        order: 0

```
in tangram play it's work but with android sdk it show me black screen
