### ISSUE TITLE
actual transparency of polygon is half of what it specified in `color`

### ISSUE THREAD

**Issue by westnordost** [tangrams/tangram-es#2333]
Have a style like this and go to [53.59579/9.94521](https://www.openstreetmap.org/way/612211229#map=19/53.59555/9.94558):

```yaml
sources:
    jawg:
        type: MVT
        url: https://tile.jawg.io/streets-v2/{z}/{x}/{y}.pbf
        max_zoom: 16
        url_params:
            access-token: Rqx0Qqc3TAHCG5MVXmxSAkaSgwm5nVSq4fV8IeTxiq9cieOQFfOt5BsYjK8Cwkqr
styles:
    buildings-style:
        base: polygons
        blend: translucent
layers:
    buildings:
        data: { source: jawg, layer: building }
        draw:
            buildings-style:
                order: 100
                color: rgba(0,0,0,0.25)
scene:
    background:
        color: "#ffffff"
```

**RESULT:**

You'll see this (as if alpha was `0.5`):

![image](https://user-images.githubusercontent.com/4661658/193478356-4d20e506-eee9-4e35-8fed-0853ffd9f4b0.png)

**EXPECTED RESULT:**

![image](https://user-images.githubusercontent.com/4661658/193478387-2ef4c531-0c2f-40a2-9944-93f9db7bc324.png)

**ENVIRONMENT:**

0.17.1, Android 12

**MORE INFORMATION:**

The bug only appears for tangram-es. Tangram (JS) does not have this bug. So if you input the above style in https://play.tangram.city/?#20.00000/53.59567/9.94527 , the transparency will be correct.

When the transparency is 0.5, the polygon will be drawn at full alpha in tangram-es.
