### ISSUE TITLE
line style misbehaves when no width defined for outline

### ISSUE THREAD

**Issue by tallytalwar** [tangrams/tangram-es#533]
Example Style Sheet:
```
scene:
    background:
        color: '#8db7d5'
cameras:
    iso-camera:
        # Manhattan
        position: [-74.00976419448854, 40.70532700869127, 16]
        type: isometric
        axis: [0, 1]
        active: false
    perspective-camera:
        # Manhattan
        position: [-74.00976419448854, 40.70532700869127, 16]
        type: perspective #currently ignored
        focal_length: [[16, 2], [20, 6]] # currently ignored
        vanishing_point: [-250, -250] # currently ignored
        active: true

lights:
    light1:
        type: directional
        origin: world
        direction: [1, 1, -1]
        diffuse: [.3, .3, .3, 1.]
        ambient: [0.7, 0.7, 0.7, 1.]

sources:
    osm:
        type: MVT
        url:  https://vector.mapzen.com/osm/all/{z}/{x}/{y}.mvt
        max_zoom: 18

layers:
    earth:
        data: { source: osm }
        draw:
            polygons:
                order: 0
                color: '#f0ebeb'
    landuse:
        data: { source: osm }
        draw:
            polygons:
                order: 1
                color: '#fffffa'
    water:
        data: { source: osm }
        draw:
            polygons:
                order: 3
                color: '#8db7d5'
    roads:
        data: { source: osm }
        #filter: { kind: rail, not: { railway: [subway, light_rail] } }
        draw:
            lines:
                order: 4
                color: [0.588,0.671,0.698]
                width: [[12,0px],[13,0.25px],[14,0.4px],[15,0.75px],[16,0.75px],[18,1px]]
                outline:
                    order: 5
                    #width: 1px
                    color: red
        service:
            filter: { service: true }
            draw:
                lines:
                    color: [0.588,0.671,0.698]
                    width: [[14,0px],[15,0.5px],[16,0.75px],[17,1px],[18,0.7m]]
                    outline:
                        order: 5
                        #width: 1px
                        color: red

```
