### ISSUE TITLE
Light position param in meters/pixels parsing

### ISSUE THREAD

**Issue by karimnaaji** [tangrams/tangram-es#598]
tangram-es should be able to parse light position params in `meters`/`pixels`:

Something like,
```yaml
lights:
    light:
        position: [0, 0m, 100px]
```
gives currently some parsing errors.

https://github.com/tangrams/tangram-docs/blob/gh-pages/pages/lights.md#point-light-properties
