### ISSUE TITLE
Regression on style mixing uniform shader block

### ISSUE THREAD

**Issue by karimnaaji** [tangrams/tangram-es#618]
While adding uniform arrays, I discovered that we might have done a regression on uniform shader mixing (probably define too).

This currently fails on master, it seems that `heightglowline` doesn't get mixed properly for the block uniforms:

```yaml
     heightglow:
         base: polygons
         shaders:
             uniforms:
                  u_test: 800.0
             blocks:
                  color: "color.rgb += vec3(position.z / u_test);"
     heightglowline:
         base: lines
         mix: heightglow
```

Compilation error on the shader while compiling `heightglowline`:
```
ERROR shaderProgram.cpp:212: Compiling shader:
ERROR: 0:451: Use of undeclared identifier 'u_test'
```

We should consolidate the test case coverage for those.

**Comment by tallytalwar** [comment]
So it looks like child style `uniforms` and `defines` will not be mixed properly, if it does not have a `map` on the `shaders` element.

Refer lines:
https://github.com/tangrams/tangram-es/blob/master/core/src/scene/styleMixer.cpp#L119
https://github.com/tangrams/tangram-es/blob/master/core/src/scene/styleMixer.cpp#L204

You can confirm this by using the following (which works):

```
yaml
     heightglow:
         base: polygons
         shaders:
             uniforms:
                  u_test: 800.0
             blocks:
                  color: "color.rgb += vec3(position.z / u_test);"
     heightglowline:
         base: lines
         mix: heightglow
         shaders:
             uniforms:
                  u_works: 1.
```
