### ISSUE TITLE
Data source configuration should include setting URL parameters

### ISSUE THREAD

**Issue by blair1618** [tangrams/tangram-es#663]
```yaml
sources:
   osm:
      type: TopoJSON
      url: http://vector.mapzen.com/osm/all/{z}/{x}/{y}.topojson
      url_params:
         api_key: vector-tiles-HqUVidw
```

Tangram-JS implementation: https://github.com/tangrams/tangram/pull/204
