### ISSUE TITLE
Support for raster base map in Tangram [Android]

### ISSUE THREAD

**Issue by hak-tpl** [tangrams/tangram-es#718]
Is there any way to load raster images as base map? Like Satellite images as base map and plotting vector data (POIs, Roads etc) over the raster images.

I've tried :
```
sources:
    local:
        type: GeoJSON
        url:  http://182.191.123.138:8001/composite/{z}/{x}/{y}.json
        max_zoom: 22

    stamen-terrain:
        type: Raster
        url:  https://terrain-preview.mapzen.com/normal/{z}/{x}/{y}.png
```
with 
```
layers:
    terrain:
        data: { source: stamen-terrain }
        draw:
            raster:
                order: 0
     roads: ....
     pois:  .....
```

But it just doesn't load the raster map. I want my vector data to be plotted over raster base map.
