### ISSUE TITLE
iOS Picking Feature

### ISSUE THREAD

**Issue by sajadkhan** [tangrams/tangram-es#743]
When I tap on a map I want to check if its hitting a feature (point, line or polygon). 
I have checked the `pickFeaturesAt(float _x, float _y)` in tangram.cpp but its only checking for Labels (`labels.h`). 
I'm not sure what actually label is and does it have to do any thing with feature. (`ProjectedFeature`). 
Can you please guide me on this. If this is supported? Or am I using the wrong method? 
I used this functionality for POIs (points) in android successfully. Kinda stuck with iOS, any help will be appreciated. 
Thanks
Sajad.

**Comment by karimnaaji** [comment]
Hey @sajadkhan , our feature picking only checks for labels currently. We plan to update it to be able to pick any feature in the future (polygon/lines). 

For now, if you query `pickFeatureAt` you should have a `TouchItem` with a set of properties that you can iterate through (See https://github.com/tangrams/tangram-es/blob/master/core/src/tangram.h#L147_L153), If you want to see how this struct is described: https://github.com/tangrams/tangram-es/blob/master/core/src/data/properties.h but keep in mind that those queries are only for point and line labels. 

Keep in mind that this will be wrapped within the iOS SDK so the usage would more iOS friendly (in a similar way as our Android SDK does) so it is subject to change; but for now I guess that you can already use those structs if you need to do so.

On another note, don't forget to set the properties in the stylesheet (`interactive: true`) for the required features; see https://mapzen.com/documentation/tangram/draw/#interactive.

**Comment by bcamper** [comment]
As to your question of what a "label" is, it encompasses text and
icons/sprites.

**Comment by sajadkhan** [comment]
Thanks for the explanation. Can you please give me an example how to add label on the scene? That will be really helpful. 
And as its mentioned in previous threads also that iOS SDK is under progress. Can you give an estimation for that? I mean when it will be launched?

**Comment by karimnaaji** [comment]
@msmollin is leading the work on the Tangram iOS SDK, he can give a more detailed timeframe about it.

Labels would be created when any layer would be matching with a text draw rule or point draw rule under it. Here is an example on how to add road _labels_:
```yaml
layers:
    roads:
        data: { source: mapzen }
        filter: { not: { kind: ferry } }
        labels:
            filter:
                name: true
            draw:
                text:
                    font:
                        fill: white
                        family: Helvetica
                        size: 11px

            highway:
                filter: { kind: highway }
                draw:
                    text:
                        font:
                            size: 12px
                            weight: bold
```
See also for documentation about those: 
- https://mapzen.com/documentation/tangram/Styles-Overview/#points
- https://mapzen.com/documentation/tangram/Styles-Overview/#text
