### ISSUE TITLE
Indoor map

### ISSUE THREAD

**Issue by NabilNoaman** [tangrams/tangram-es#766]
Hi All,

I want to thank you for the great framework.

Is indoor map on tangram roadmap ?

**Comment by nvkelso** [comment]
Can you tell me more about your use case? Do you have indoor data you want to display / style? Or are you asking about indoor positioning?

**Comment by NabilNoaman** [comment]
I have building data & want to draw my location (provided from IPS) on it.

**Comment by nvkelso** [comment]
You'd like to overlay your own building geometry data on the map so you can show the customers location on it?

You can import the basic Mapzen vector tiles, and then also import custom tiles with your buildings. You could do that using TileStache or a custom confit of our tilezen stack.

**Comment by NabilNoaman** [comment]
I don't need basemap just want to render my building floors map and switch between them.

**Comment by bcamper** [comment]
You could have different features corresponding to each of your building floors, tied together by a single id for each building. Then you could control the visibility of each building floor individually at run-time with `global` properties. Something like this, with a unique `building_id` for each building, and feature properties for `footprint` to indicate an exterior polygon, and `floor` to indicate the floor number of the interior floorplan polygons.

```
global:
   selected:
      building_id: null
      floor: 0

layers:
   buildings:
      data: { ... }
      
      footprints:
         filter: { footprint: true }
         draw:      
            # draw building exteriors
            polygons:
               ...

      floor:
         filter: |
            function () { 
               return feature.building_id === global.selected.building_id && 
                         feature.floor === global.selected.floor;
            }
         draw:
            # draw the selected floor
            polygons:
               ...
```

If you go down this or a similar path and have questions, please let us know.
