### ISSUE TITLE
Fully support inlining of texture definition

### ISSUE THREAD

**Issue by tallytalwar** [tangrams/tangram-es#771]
Documentation: https://github.com/tangrams/tangram-docs/blob/gh-pages/pages/textures.md

Example Usage:
```
cameras:
    perspective-camera:
        # Manhattan
        position: [-74.00976419448854, 40.70532700869127, 16]
        type: perspective
        fov: 45
        active: true

lights:
    light1:
        type: directional
        origin: world
        direction: [1, 1, -1]
        diffuse: [.3, .3, .3, 1.]
        ambient: [0.7, 0.7, 0.7, 1.]

styles:
    icons:
        base: points
        texture: 
            url: https://raw.githubusercontent.com/tangrams/tangram-es/master/scenes/img/poi_icons_32.png
            sprites:
                restaurant: [0, 777, 32, 32]
    
sources:
    osm:
        type: MVT
        url:  https://vector.mapzen.com/osm/all/{z}/{x}/{y}.mvt
        max_zoom: 18
        url_params:
            api_key: vector-tiles-tyHL4AY

layers:
    earth:
        data: { source: osm }
        draw:
            polygons:
                order: 0
                color: '#f0ebeb'
    landuse:
        data: { source: osm }
        draw:
            polygons:
                order: 1
                color: '#fffffa'
        
    water:
        data: { source: osm }
        draw:
            polygons:
                order: 3
                color: '#8db7d5'
    
    poi_icons:
        data: { source: osm, layer: pois }
        # examples of different icons mapped to feature properties
        icons:
            restaurant:
                filter: { kind: [restaurant] }
                draw: 
                    icons: 
                        #color: blue
                        sprite: restaurant
```

Maybe requires some discussion on how much of inlining should be allowed with textures.
