### ISSUE TITLE
MapData from old map view is not cleared

### ISSUE THREAD

**Issue by westnordost** [tangrams/tangram-es#781]
Again, not sure if I do something wrong or if it is a bug:

Given this code in the map activity:
```
private MapView mapView;

@Override
protected void onCreate(Bundle savedInstanceState)
{
	super.onCreate(savedInstanceState);
	setContentView(R.layout.activity_main);
	mapView = (MapView) view.findViewById(R.id.map);
	mapView.getMapAsync(new MapView.OnMapReadyCallback()
	{
		@Override public void onMapReady(MapController ctrl)
		{
			MapData mapData = ctrl.addDataLayer("osmagent_quests");
			LngLat testPoint= new LngLat(10.0,53.0);
			Map<String, String> props = new HashMap<>();
			props.put("type", "point");
			mapData.addPoint(testPoint, props);
		}
	}, "scene.yaml");
}

@Override public void onDestroy()
{
	super.onDestroy();
	if(mapView != null) mapView.onDestroy();
}
```
and a scene.yaml that contains this
```
textures:
    quest:
        url: quest.png

styles:
    quest-marker:
        base: points
        texture: quest
        blend: overlay

layers:
    quests:
        data: { source: osmagent_quests }
        draw:
            quest-marker:
                size: 36px
                color: '#ff0000'
```
and assuming that `quest.png` is **half transparent**, then when I first start the application, the point is rendered fine, but if I make the Activity and thus the map be recreated by i.e. rotating the screen,  the icon becomes more and more solid the more often I do it.
So it looks as if the data from DataLayers is not cleared on onDestroy of the mapview.
