### ISSUE TITLE
how can i use offline .mvt data in Linux

### ISSUE THREAD

**Issue by TGISer** [tangrams/tangram-es#801]
for example my local url is :

/home/tgiser/tiles/{z}/{x}/{y}.mvt

how can i use it.

thank you for your help!

**Comment by blair1618** [comment]
Try creating a data source in your scene file like this:
```yaml
sources:
  local-tiles:
    type: MVT
    url: file:///home/tgiser/tiles/{z}/{x}/{y}.mvt
```
Let me know how it goes!
