### ISSUE TITLE
steps of drawing

### ISSUE THREAD

**Issue by ivangorelow** [tangrams/tangram-es#958]
```
marker_cam_on:
                 data: { source: marker_cam_on }
                 draw:
                     priority: 1
                     sdk-point-overlay-green:
                         interactive: true
                         sprite: segment-green
                         size: [24px,24px]
                         collide: false
                         anchor: top
                         transition:
                                         [show, hide]:
                                             time: 0s
```

I'd like to draw this layer in the first step, is it possiblle?

**Comment by ivangorelow** [comment]
because sometimes I lose this layer

**Comment by ivangorelow** [comment]
```
sdk-point-overlay-green:
            base: points
            texture: markerIcon
            priority: 1
            interactive: true
            blend: overlay
            blend_order: 4
```
