### ISSUE TITLE
Collision in draw group

### ISSUE THREAD

**Issue by westnordost** [tangrams/tangram-es#989]
I have the following use case: 

![markers](https://cloud.githubusercontent.com/assets/4661658/18993610/4e9a7f86-8724-11e6-9ad9-6fa304314148.png)
When adding a point as a marker, I want to draw the map pin/marker first and then the icon of that marker on top instead of one marker+icon image for every different marker.
This is (almost) possible with the following scene.yaml:

``` yaml
textures:
    quests:
        url: quests@2x.png
        sprites:
            signpost: [0,0,64,64]
            marker: [127,127,90,90]

styles:
    quest-icons:
        base: points
        texture: quests
        blend: overlay

layers:
    questslayer:
        data: { source: osmagent_quests }
        draw:
            questicon:
                size: 32px
                sprite: function() { return feature.kind }
                style: quest-icons
                offset: [12px, -51px]
                anchor: center
            markericon:
                size: 45px
                anchor: top
                offset: [5px, 5px]
                sprite: marker
                style: quest-icons
```

However, currently (0.4.2), the drawing of the `questicon` collides with the drawing of the `markericon` unless I specify `collide=false` for both because even elements within one sublayer but within different draw groups can collide. Ss far as I can see, there is currently no way to do this without disabling collision (which is not desirable).

So, I am posing the question: If is is desirable that the (drawings of) the one and same map feature can collide with itself, is there some way to define "collision groups"?
