### ISSUE TITLE
Revise 'transition' scene file syntax

### ISSUE THREAD

**Issue by matteblair** [tangrams/tangram-es#997]
This syntax:

``` yaml
transition:
  [show, hide]:
    time: 0s
```

is currently a supported way of specifying fade durations for point styles in tangram-es. Although it's well-formed YAML and yaml-cpp can grok it just fine, many tools don't correctly support map keys that aren't simple scalar values (see the discussion on this commit https://github.com/tangrams/tron/commit/53a1b143b93818b5f1c7c92a3f5856f162275dbc).

For practical expediency, it may be better to deprecate this syntax in favor of an alternative that is more easily digestible by common tools.

**Comment by bcamper** [comment]
The simplest alternative that comes to mind is to define each action explicitly:
```
transition:
  show: { time: 0s }
  hide: { time: 0s }
```

This could also potentially include a `default` setting to simplify blanket setting actions (assuming a future where there are more state transitions):
```
transition:
  default: { time: 0s }
  hide: { time: 0.5s }
```

We could do something else like use array syntax for actions, but it seems unwieldy and I prefer to avoid "array of objects" structures like this when possible because I think it's easy to get tripped up in the YAML indentation.
```
transitions:
  - actions: [show, hide]
    time: 0s
  - actions: [something]
    time: 1s
```

Others?

**Comment by blair1618** [comment]
The first syntax,
```yaml
transition:
  show: { time: 0s }
  hide: { time: 0s }
```
is already supported. We can just use this in all cases where we used the array-keyed syntax before.
